from django.urls import path

from . import views

app_name = "inventory"

urlpatterns = [
    path("", views.browse, name="browse"),
    path("kiosk-autologin/", views.kiosk_autologin, name="kiosk_autologin"),
    path("scan/", views.scan, name="scan"),
    path("go/", views.go, name="go"),
    path("jump/", views.jump_to_container, name="jump_to_container"),
    path("search/", views.parts_search, name="parts_search"),
    path("tagging/", views.tagging_list, name="tagging_list"),
    path("tagging/<int:pk>/update/", views.tagging_update, name="tagging_update"),
    path("api/locate/", views.api_locate_part, name="api_locate_part"),
    path("containers/<int:number>/", views.container_detail, name="container_detail"),
    path(
        "containers/<int:number>/register-barcode/",
        views.register_container_barcode,
        name="register_container_barcode",
    ),
    path("drawers/<int:pk>/", views.drawer_detail, name="drawer_detail"),
    path("drawers/<int:pk>/register-barcode/", views.register_drawer_barcode, name="register_drawer_barcode"),
    path("drawers/<int:pk>/locate-led/", views.locate_drawer_led, name="locate_drawer_led"),
    path("intake/", views.part_intake, name="part_intake"),
    path("parts/<int:pk>/", views.part_detail, name="part_detail"),
    path("parts/<int:pk>/add-stock/", views.add_stock_item, name="add_stock_item"),
    path("parts/<int:pk>/add-photo/", views.add_part_photo, name="add_part_photo"),
    path("stock/<int:pk>/update-quantity/", views.update_stock_quantity, name="update_stock_quantity"),
    path("stock/<int:pk>/update-bin/", views.update_stock_bin, name="update_stock_bin"),
    path("stock/<int:pk>/locate/", views.locate_stock_item, name="locate_stock_item"),
    path("stock/<int:pk>/delete/", views.delete_stock_item, name="delete_stock_item"),
    path("containers/<int:number>/delete/", views.delete_container, name="delete_container"),
    path("labels/", views.labels, name="labels"),
    path("labels/generate/", views.generate_and_print_labels, name="generate_labels"),
    path("labels/print/", views.print_labels, name="print_labels"),
    path("barcode/<str:code>.svg", views.barcode_svg, name="barcode_svg"),
    path("projects/", views.project_list, name="project_list"),
    path("projects/<int:pk>/", views.project_detail, name="project_detail"),
    path("projects/<int:pk>/build/", views.build_project, name="build_project"),
    path("reorder/", views.reorder, name="reorder"),
    path("export/", views.export_inventory, name="export_inventory"),
    path("reference/", views.reference_list, name="reference_list"),
    path("reference/resistor-calculator/", views.resistor_calculator, name="resistor_calculator"),
    path("lights/", views.light_controls, name="light_controls"),
    path("lights/set-defaults/", views.led_set_defaults, name="led_set_defaults"),
    path("lights/room-light/", views.led_room_light, name="led_room_light"),
    path("lights/demo/", views.led_demo, name="led_demo"),
    path("bins/", views.bin_setup, name="bin_setup"),
    path("bins/scan/", views.bin_scan, name="bin_scan"),
    path("bins/<int:pk>/scan/", views.api_scan_bin, name="api_scan_bin"),
    path("containers/<int:number>/add-photo/", views.add_container_photo, name="add_container_photo"),
    path("containers/<int:number>/add-note/", views.add_intake_note, name="add_intake_note"),
    path("intake/new-box/", views.quick_add_container, name="quick_add_container"),
    path("intake/queue/", views.intake_queue, name="intake_queue"),
    path("intake/notes/<int:pk>/reviewed/", views.mark_intake_note_reviewed, name="mark_intake_note_reviewed"),
]
