from django.urls import path

from . import views

app_name = "inventory"

urlpatterns = [
    path("", views.browse, name="browse"),
    # The app's own login/logout. Before these existed, signing in meant the Django
    # admin login page and /login/ was a 404.
    path("login/", views.AppLoginView.as_view(), name="login"),
    path("logout/", views.AppLogoutView.as_view(), name="logout"),
    path("kiosk-autologin/", views.kiosk_autologin, name="kiosk_autologin"),
    path("scan/", views.scan, name="scan"),
    path("go/", views.go, name="go"),
    path("jump/", views.jump_to_container, name="jump_to_container"),
    path("search/", views.parts_search, name="parts_search"),
    path("tagging/", views.tagging_list, name="tagging_list"),
    path("tagging/<int:pk>/update/", views.tagging_update, name="tagging_update"),
    path("api/locate/", views.api_locate_part, name="api_locate_part"),
    path("api/add/", views.api_add_intake_note, name="api_add_intake_note"),
    path("containers/<int:number>/", views.container_detail, name="container_detail"),
    path(
        "containers/<int:number>/register-barcode/",
        views.register_container_barcode,
        name="register_container_barcode",
    ),
    path("drawers/<int:pk>/", views.drawer_detail, name="drawer_detail"),
    path("drawers/<int:pk>/register-barcode/", views.register_drawer_barcode, name="register_drawer_barcode"),
    path("drawers/<int:pk>/locate-led/", views.locate_drawer_led, name="locate_drawer_led"),
    path("intake/", views.part_intake, name="part_intake"),
    path("parts/<int:pk>/", views.part_detail, name="part_detail"),
    path("parts/<int:pk>/add-stock/", views.add_stock_item, name="add_stock_item"),
    path("parts/<int:pk>/add-photo/", views.add_part_photo, name="add_part_photo"),
    path("stock/<int:pk>/update-quantity/", views.update_stock_quantity, name="update_stock_quantity"),
    path("stock/<int:pk>/update-bin/", views.update_stock_bin, name="update_stock_bin"),
    path("stock/<int:pk>/locate/", views.locate_stock_item, name="locate_stock_item"),
    path("stock/<int:pk>/delete/", views.delete_stock_item, name="delete_stock_item"),
    path("containers/<int:number>/delete/", views.delete_container, name="delete_container"),
    path("labels/", views.labels, name="labels"),
    path("labels/generate/", views.generate_and_print_labels, name="generate_labels"),
    path("labels/print/", views.print_labels, name="print_labels"),
    path("barcode/<str:code>.svg", views.barcode_svg, name="barcode_svg"),
    path("labels/custom/", views.custom_label, name="custom_label"),
    path("projects/", views.project_list, name="project_list"),
    path("projects/create/", views.create_project, name="create_project"),
    path("projects/<int:pk>/", views.project_detail, name="project_detail"),
    path("projects/<int:pk>/build/", views.build_project, name="build_project"),
    path("reorder/", views.reorder, name="reorder"),
    path("enrichment/", views.enrichment_queue, name="enrichment_queue"),
    path("enrichment/classify/", views.run_enrichment_classification, name="run_enrichment_classification"),
    path("enrichment/flag/<int:pk>/", views.flag_part_for_enrichment, name="flag_part_for_enrichment"),
    path("enrichment/bulk-classify/", views.bulk_classify, name="bulk_classify"),
    path("enrichment/enrich-ai/", views.enrich_pending_with_ai, name="enrich_pending_with_ai"),
    path("enrichment/scan-ai/", views.ai_scan_candidates, name="ai_scan_candidates"),
    path("export/", views.export_inventory, name="export_inventory"),
    path("export/csv/", views.export_csv, name="export_csv"),
    path("import/csv/", views.import_csv, name="import_csv"),
    path("shopping-list/", views.shopping_list, name="shopping_list"),
    path("shopping-list/add/<int:pk>/", views.shopping_list_add, name="shopping_list_add"),
    path("shopping-list/<int:pk>/toggle/", views.shopping_list_toggle, name="shopping_list_toggle"),
    path("shopping-list/clear/", views.shopping_list_clear, name="shopping_list_clear"),
    path("shopping-list/export.txt", views.shopping_list_export, name="shopping_list_export"),
    # Community: the connections page, and the single endpoint peers call.
    path("community/", views.community_connections, name="community_connections"),
    path("community/map/", views.community_map, name="community_map"),
    path("community/map/sync/", views.community_sync_pins, name="community_sync_pins"),
    path("community/search/", views.community_network_search, name="community_network_search"),
    path("community/messages/", views.community_message_inbox, name="community_messages"),
    path("community/messages/send/", views.community_send_message, name="community_send_message"),
    path("community/messages/<int:message_id>/retry/", views.community_retry_message, name="community_retry_message"),
    path("community/messages/<int:peer_id>/", views.community_message_thread, name="community_message_thread"),
    path("community/connect/", views.community_join, name="community_join"),
    path("community/code/", views.community_issue_code, name="community_issue_code"),
    path("community/<int:pk>/update/", views.community_update_peer, name="community_update_peer"),
    path("community/<int:pk>/revoke/", views.community_revoke, name="community_revoke"),
    path("community/<int:pk>/forget/", views.community_forget, name="community_forget"),
    path("community/<int:pk>/block/", views.community_block, name="community_block"),
    path("community/<int:pk>/unblock/", views.community_unblock, name="community_unblock"),
    path("api/community/claim/", views.api_community_claim, name="api_community_claim"),
    path("api/community/pins/", views.api_community_pins, name="api_community_pins"),
    path("api/community/peer-search/", views.api_community_peer_search, name="api_community_peer_search"),
    path("api/community/messages/", views.api_community_messages, name="api_community_messages"),
    # Setup and settings are the same pages, deliberately — see inventory/wizard.py.
    # Every one stays reachable after setup, because "change my workshop's name" should
    # not need a rebuild or a trip into /admin/.
    path("setup/", views.setup_hub, name="setup_hub"),
    path("setup/account/", views.setup_account, name="setup_account"),
    path("setup/site/", views.setup_site, name="setup_site"),
    path("setup/lights/", views.setup_lights, name="setup_lights"),
    path("setup/flash/", views.setup_flash, name="setup_flash"),
    path("setup/printer/", views.setup_printer, name="setup_printer"),
    path("setup/reference/", views.setup_reference, name="setup_reference"),
    path("setup/community/", views.setup_community, name="setup_community"),
    path("setup/access/", views.setup_access, name="setup_access"),
    path("setup/email/", views.setup_email, name="setup_email"),
    path("setup/ai/", views.setup_ai, name="setup_ai"),
    path("setup/finish/", views.setup_finish, name="setup_finish"),
    path("help/", views.help_index, name="help_index"),
    path("help/<slug:slug>/", views.help_topic, name="help_topic"),
    path("feedback/", views.feedback, name="feedback"),
    path("api/feedback/", views.api_feedback, name="api_feedback"),
    path("reference/", views.reference_list, name="reference_list"),
    # The library is the owner's to arrange, so it gets real editing pages rather than
    # living only in /admin/.
    path("reference/manage/", views.reference_manage, name="reference_manage"),
    path("reference/add/", views.reference_add, name="reference_add"),
    path("reference/<int:pk>/edit/", views.reference_edit, name="reference_edit"),
    path("reference/<int:pk>/delete/", views.reference_delete, name="reference_delete"),
    path("reference/<int:pk>/move/", views.reference_move, name="reference_move"),
    path("reference/<int:pk>/archive/", views.reference_archive, name="reference_archive"),
    path("reference/categories/add/", views.reference_category_add, name="reference_category_add"),
    path("reference/categories/<int:pk>/edit/", views.reference_category_edit, name="reference_category_edit"),
    path("reference/categories/<int:pk>/delete/", views.reference_category_delete, name="reference_category_delete"),
    path("reference/resistor-calculator/", views.resistor_calculator, name="resistor_calculator"),
    path("lights/", views.light_controls, name="light_controls"),
    path("lights/set-defaults/", views.led_set_defaults, name="led_set_defaults"),
    path("lights/room-light/", views.led_room_light, name="led_room_light"),
    path("lights/demo/", views.led_demo, name="led_demo"),
    path("bins/", views.bin_setup, name="bin_setup"),
    path("bins/scan/", views.bin_scan, name="bin_scan"),
    path("bins/<int:pk>/scan/", views.api_scan_bin, name="api_scan_bin"),
    path("bins/<int:pk>/", views.bin_detail, name="bin_detail"),
    path("bins/<int:pk>/register-barcode/", views.register_bin_barcode, name="register_bin_barcode"),
    path("bins/<int:pk>/locate/", views.locate_bin, name="locate_bin"),
    path("bins/<int:pk>/add-sub-bin/", views.add_sub_bin, name="add_sub_bin"),
    path("sub-bins/<int:pk>/register-barcode/", views.register_sub_bin_barcode, name="register_sub_bin_barcode"),
    path("sub-bins/<int:pk>/delete/", views.delete_sub_bin, name="delete_sub_bin"),
    path("containers/<int:number>/add-photo/", views.add_container_photo, name="add_container_photo"),
    path("containers/<int:number>/add-note/", views.add_intake_note, name="add_intake_note"),
    path("intake/new-box/", views.quick_add_container, name="quick_add_container"),
    path("intake/queue/", views.intake_queue, name="intake_queue"),
    path("intake/add/", views.bulk_intake, name="bulk_intake"),
    path("intake/add-location/", views.add_intake_location, name="add_intake_location"),
    path("intake/notes/<int:pk>/reviewed/", views.mark_intake_note_reviewed, name="mark_intake_note_reviewed"),
    path("intake/notes/<int:pk>/assign/", views.assign_intake_note_container, name="assign_intake_note_container"),
]
