# Generated by Django 6.1 on 2026-08-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text="Original 'Box' number from the spreadsheet", unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('container_type', models.CharField(help_text="e.g. 'large black tote', 'custom', 'cabinets'", max_length=100)),
                ('barcode_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'drawer b2'", max_length=100)),
                ('barcode_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawers', to='inventory.container')),
            ],
            options={
                'ordering': ['container__number', 'label'],
                'unique_together': {('container', 'label')},
            },
        ),
        migrations.AddField(
            model_name='container',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='inventory.location'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=300)),
                ('is_electronic', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('min_quantity', models.PositiveIntegerField(blank=True, help_text='Reorder threshold (Phase 5)', null=True)),
                ('reorder_url', models.URLField(blank=True)),
                ('enrichment_status', models.CharField(choices=[('not_needed', 'Not needed'), ('pending', 'Pending'), ('done', 'Done')], default='not_needed', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('quantity_raw', models.CharField(blank=True, help_text="Original spreadsheet value, e.g. '10 aprox'", max_length=50)),
                ('source_notes', models.CharField(blank=True, help_text='Non-drawer freeform notes from the spreadsheet', max_length=300)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.container')),
                ('drawer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.drawer')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.part')),
            ],
            options={
                'ordering': ['container__number', 'drawer__label', 'part__name'],
            },
        ),
    ]
