# Generated by Django 6.1 on 2026-08-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/')),
                ('doc_type', models.CharField(choices=[('datasheet', 'Datasheet'), ('pinout', 'Pinout'), ('wiring', 'Wiring diagram'), ('product_page', 'Product page (archived)'), ('image', 'Image')], max_length=20)),
                ('source_url', models.URLField(blank=True, help_text='Where this was originally fetched from')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.part')),
            ],
            options={
                'ordering': ['part', 'doc_type'],
            },
        ),
    ]
