# Generated by Django 6.1 on 2026-08-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_part_enrichment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['project', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_built', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('built_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='inventory.bomrevision')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='inventory.project')),
            ],
            options={
                'ordering': ['-built_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_consumed', models.PositiveIntegerField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.build')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='build_consumptions', to='inventory.part')),
            ],
        ),
        migrations.AddField(
            model_name='bomrevision',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='inventory.project'),
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='inventory.part')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.bomrevision')),
            ],
            options={
                'ordering': ['part__name'],
                'unique_together': {('revision', 'part')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bomrevision',
            unique_together={('project', 'version')},
        ),
    ]
