# Generated by Django 6.1 on 2026-08-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_bomrevision_project_build_buildconsumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='enrichment_status',
            field=models.CharField(choices=[('not_needed', 'Not needed'), ('pending', 'Pending'), ('needs_clarification', 'Needs clarification (ask Seth)'), ('needs_review', 'Needs review'), ('done', 'Done')], default='not_needed', max_length=20),
        ),
    ]
