# Generated by Django 6.1 on 2026-08-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_part_enrichment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('raspberry_pi', 'Raspberry Pi'), ('arduino', 'Arduino'), ('electronics', 'Electronics reference'), ('3d_printing', '3D printing')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True, help_text='Canonical/live source, always shown as a link out')),
                ('file', models.FileField(blank=True, help_text='Locally cached copy (image/PDF) so this survives even if the source goes away', null=True, upload_to='reference/%Y/')),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
