# Generated by Django 6.1 on 2026-08-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_referencedoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='datasheet_url',
            field=models.URLField(blank=True, help_text='Quick reference link — not a locally cached copy, see Attachments for that'),
        ),
    ]
