# Generated by Django 6.1 on 2026-08-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_part_datasheet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawer',
            name='led_count',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of LEDs marking this drawer', null=True),
        ),
        migrations.AddField(
            model_name='drawer',
            name='led_start_index',
            field=models.PositiveIntegerField(blank=True, help_text='First LED index (0-based) for this drawer on that strip', null=True),
        ),
        migrations.AddField(
            model_name='drawer',
            name='led_strip',
            field=models.CharField(blank=True, help_text="Logical WS2812B strip name/ID this drawer's indicator LEDs are on, e.g. 'cabinet1'", max_length=100),
        ),
    ]
