# Generated by Django 6.1 on 2026-08-31 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_drawer_led_count_drawer_led_start_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawer',
            name='led_count',
        ),
        migrations.RemoveField(
            model_name='drawer',
            name='led_start_index',
        ),
        migrations.RemoveField(
            model_name='drawer',
            name='led_strip',
        ),
        migrations.CreateModel(
            name='DrawerLedSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led_strip', models.CharField(help_text="Logical WS2812B strip name/ID, e.g. 'cabinet1-left'", max_length=100)),
                ('led_start_index', models.PositiveIntegerField(help_text='First LED index (0-based) for this drawer on that strip')),
                ('led_count', models.PositiveIntegerField(default=1, help_text='Number of LEDs marking this drawer on this strip')),
                ('drawer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_segments', to='inventory.drawer')),
            ],
            options={
                'ordering': ['drawer', 'led_strip'],
            },
        ),
    ]
