# Generated by Django 6.1 on 2026-09-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_drawer_led_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='bin_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Which of the drawer's 16 bins (1-16, 4 rows of 4) this sits in, if known", null=True),
        ),
    ]
