# Generated by Django 6.1 on 2026-09-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockitem_bin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='container_photos/%Y/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.container')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(choices=[('voice', 'Voice'), ('typed', 'Typed')], default='typed', max_length=10)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_notes', to='inventory.container')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_number', models.PositiveSmallIntegerField(help_text='1-16 (4 rows of 4)')),
                ('barcode_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('drawer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='inventory.drawer')),
            ],
            options={
                'ordering': ['drawer__container__number', 'drawer__label', 'bin_number'],
                'unique_together': {('drawer', 'bin_number')},
            },
        ),
    ]
