# Generated by Django 6.1 on 2026-09-11 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_containerphoto_intakenote_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='1-4 within the bin')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium')], default='small', max_length=10)),
                ('barcode_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_bins', to='inventory.bin')),
            ],
            options={
                'ordering': ['bin', 'position'],
                'unique_together': {('bin', 'position')},
            },
        ),
    ]
