# Generated by Django 6.1 on 2026-09-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_subbin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakenote',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_notes', to='inventory.container'),
        ),
    ]
