# Generated by Django 6.1 on 2026-09-13 17:33

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_intakenote_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=64, unique=True)),
                ('private_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'community identity',
            },
        ),
        migrations.CreateModel(
            name='CommunityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discoverable', models.BooleanField(default=False, help_text="Appear as an anonymous pin on other workshops' maps. Off by default. Independent of who can search this instance — see Peer.shares_parts.")),
                ('display_name', models.CharField(blank=True, help_text='Optional. The map shows anonymous pins, so this is not published by default.', max_length=100)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, e.g. GB', max_length=2)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('location_source', models.CharField(blank=True, choices=[('outcode', 'UK outcode'), ('zip', 'US ZIP'), ('nominatim', 'Postcode via OpenStreetMap'), ('manual', 'Entered by hand')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'community profile',
            },
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Dad\'s workshop"', max_length=200)),
                ('base_url', models.URLField(help_text="Their instance's public address")),
                ('public_key', models.CharField(blank=True, help_text='Their Ed25519 signing key — their stable identity, used to verify the pins they publish', max_length=64)),
                ('inbound_api_key', models.CharField(default=inventory.models.new_api_key, help_text='The credential we issued to them, checked on requests they make to us', max_length=64, unique=True)),
                ('outbound_api_key', models.CharField(blank=True, help_text='The credential they issued to us, sent when we query them', max_length=64)),
                ('is_seed', models.BooleanField(default=False, help_text="The maintainer's instance, connected by default so a new install has a way onto the map")),
                ('exchanges_pins', models.BooleanField(default=True, help_text='Exchange anonymous map pins. Never grants access to inventory.')),
                ('shares_parts', models.BooleanField(default=False, help_text='May search categories marked shareable. Off until opted in for this specific person.')),
                ('status', models.CharField(choices=[('pending', 'Pending — asked, not yet accepted'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('contact_note', models.CharField(blank=True, help_text='How to reach them, e.g. an email. Shown on search results.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='is_shareable',
            field=models.BooleanField(default=False, help_text='Visible to connected workshops via community search. Off by default — sharing is opted into per category, and a part with no category is never shareable.'),
        ),
        migrations.CreateModel(
            name='PairingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_codes', to='inventory.peer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='inventory.peer')),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
