# Generated by Django 6.1 on 2026-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_communityidentity_communityprofile_peer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Parts', help_text='Shown in the header, every page title, and the admin.', max_length=60)),
                ('timezone', models.CharField(default='UTC', help_text='IANA name, e.g. Europe/London or America/New_York. Every timestamp displays in this zone — set it to where the workshop actually is.', max_length=64)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, e.g. GB or US. Decides whether postcodes or ZIP codes are expected when finding nearby workshops.', max_length=2)),
                ('unit_system', models.CharField(choices=[('metric', 'Metric (metres, grams)'), ('imperial', 'Imperial (feet, ounces)')], default='metric', help_text='Which units are offered first. Every unit stays selectable either way.', max_length=10)),
                ('setup_completed_at', models.DateTimeField(blank=True, help_text='When the setup wizard finished. Null means setup is still outstanding.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='default_unit',
            field=models.CharField(choices=[('ea', 'Each'), ('m', 'Metres'), ('cm', 'Centimetres'), ('mm', 'Millimetres'), ('ft', 'Feet'), ('in', 'Inches'), ('g', 'Grams'), ('kg', 'Kilograms'), ('oz', 'Ounces'), ('lb', 'Pounds'), ('ml', 'Millilitres'), ('l', 'Litres')], default='ea', help_text="What this part's quantities count. Leave as 'each' for countable parts; set metres, grams and so on for wire, tubing, filament and solder.", max_length=8),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('ea', 'Each'), ('m', 'Metres'), ('cm', 'Centimetres'), ('mm', 'Millimetres'), ('ft', 'Feet'), ('in', 'Inches'), ('g', 'Grams'), ('kg', 'Kilograms'), ('oz', 'Ounces'), ('lb', 'Pounds'), ('ml', 'Millilitres'), ('l', 'Litres')], default='', help_text="Overrides the part's unit for just this location. Blank means use the part's, which is what every pre-existing row gets — so old data reads exactly as before.", max_length=8),
        ),
        migrations.AlterField(
            model_name='part',
            name='enrichment_status',
            field=models.CharField(choices=[('not_needed', 'Not needed'), ('pending', 'Pending'), ('needs_clarification', 'Needs clarification'), ('needs_review', 'Needs review'), ('done', 'Done')], default='not_needed', max_length=20),
        ),
    ]
