# Generated by Django 6.1 on 2026-09-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_configure_existing_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='label_printer_key',
            field=models.CharField(blank=True, help_text='Shared secret for the print bridge, if it needs one.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='label_printer_url',
            field=models.CharField(blank=True, help_text='Address of the label print bridge, e.g. http://192.168.1.50:9100', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='led_controller_key',
            field=models.CharField(blank=True, help_text='Shared secret for the LED controller, if it needs one.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='led_controller_url',
            field=models.CharField(blank=True, help_text="Address of the LED 'find the part' controller, e.g. http://192.168.1.50:8080", max_length=300),
        ),
    ]
