# Generated by Django 6.1 on 2026-09-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_reference_categories_editable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencedoc',
            options={'ordering': ['category__order', 'order', 'title']},
        ),
        migrations.AddField(
            model_name='attachment',
            name='archive_attempted_at',
            field=models.DateTimeField(blank=True, help_text='When archiving was last tried, successfully or not.', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='archive_content_type',
            field=models.CharField(blank=True, help_text='What the source actually served, e.g. application/pdf.', max_length=100),
        ),
        migrations.AddField(
            model_name='attachment',
            name='archive_error',
            field=models.CharField(blank=True, help_text='Why the last attempt failed, shown to the owner.', max_length=300),
        ),
        migrations.AddField(
            model_name='attachment',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When a local copy was last saved successfully.', null=True),
        ),
        migrations.AddField(
            model_name='referencedoc',
            name='archive_attempted_at',
            field=models.DateTimeField(blank=True, help_text='When archiving was last tried, successfully or not.', null=True),
        ),
        migrations.AddField(
            model_name='referencedoc',
            name='archive_content_type',
            field=models.CharField(blank=True, help_text='What the source actually served, e.g. application/pdf.', max_length=100),
        ),
        migrations.AddField(
            model_name='referencedoc',
            name='archive_error',
            field=models.CharField(blank=True, help_text='Why the last attempt failed, shown to the owner.', max_length=300),
        ),
        migrations.AddField(
            model_name='referencedoc',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When a local copy was last saved successfully.', null=True),
        ),
        migrations.AlterField(
            model_name='referencedoc',
            name='order',
            field=models.PositiveIntegerField(default=100, help_text='Lower sorts first within its category.'),
        ),
    ]
