# Generated by Django 6.1 on 2026-09-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_referencedoc_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='starter_reference_loaded_at',
            field=models.DateTimeField(blank=True, help_text='When the starter reference library was first loaded.', null=True),
        ),
    ]
