# Generated by Django 6.1 on 2026-09-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_sitesettings_starter_reference_loaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='label_driver',
            field=models.CharField(choices=[('zpl', 'Zebra / ZPL'), ('brother_ql', 'Brother QL'), ('dymo', 'Dymo LabelWriter'), ('cups', 'Any printer via CUPS')], default='zpl', help_text='Which printer language the label renderer should produce.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='public_url',
            field=models.CharField(blank=True, help_text='The address you reach this app at, e.g. https://parts.example.com. Pasted from your tunnel or reverse proxy. Only used to check that it works.', max_length=300),
        ),
    ]
