# Generated by Django 6.1 on 2026-09-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_sitesettings_label_driver_sitesettings_public_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityprofile',
            name='country',
        ),
    ]
