# Generated by Django 6.1 on 2026-09-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_communityprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Matches the strip name used in that drawer's LED mappings, e.g. cabinet1-left", max_length=100, unique=True)),
                ('channel', models.PositiveSmallIntegerField(blank=True, help_text='The Scorpio output this strip is plugged into, 0-7', null=True)),
            ],
            options={
                'verbose_name': 'LED strip',
                'ordering': ['channel', 'name'],
            },
        ),
    ]
