# Generated by Django 6.1 on 2026-09-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_ledstrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='label_dpi',
            field=models.CharField(blank=True, help_text="The printer's dots per inch, e.g. 203. Leave blank to use the resolution that goes with the printer type above.", max_length=6),
        ),
    ]
