# Generated by Django 6.1 on 2026-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_sitesettings_label_dpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(help_text="The publishing instance's Ed25519 key — also its identity.", max_length=64, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('name', models.CharField(blank=True, help_text='Empty for an anonymous pin, which is the default.', max_length=100)),
                ('gone', models.BooleanField(default=False, help_text='Set by a signed opt-out entry. The location is deleted when this is set.')),
                ('signed_at', models.DateTimeField(help_text="The timestamp from inside the signed bytes — the owner's own clock, not ours.")),
                ('signature', models.CharField(max_length=128)),
                ('pin_version', models.PositiveSmallIntegerField(default=2, help_text='Which version of the pin format this entry was signed as. It is inside the signed bytes, so re-serving the entry under a different number would invalidate its own signature.')),
                ('hops', models.PositiveSmallIntegerField(default=0, help_text='How many relays away the origin is. Not signed — a cost and loop guard, not a fact.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'known pin',
                'ordering': ['-signed_at'],
            },
        ),
    ]
