# Generated by Django 6.1 on 2026-09-14 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_knownpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='blocked',
            field=models.BooleanField(default=False, help_text='Blocked workshops are fully cut off — no messages, no search, no pins — and cannot reconnect until unblocked.'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Received'), ('outbound', 'Sent')], max_length=8)),
                ('body', models.TextField()),
                ('remote_id', models.CharField(blank=True, max_length=64)),
                ('delivered', models.BooleanField(default=True)),
                ('read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inventory.peer')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
