# Generated by Django 6.1 on 2026-09-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_peer_blocked_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Master switch. Nothing is sent until this is on.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_from',
            field=models.CharField(blank=True, help_text='The From: address. Defaults to the SMTP account above.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_email',
            field=models.CharField(blank=True, help_text='Where notifications go. Defaults to the From: address.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_on_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_on_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_on_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text="A Gmail app password (see the page's instructions), not your login password.", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, help_text="587 is Gmail's and most providers'; 465 is the TLS-only alternative."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='STARTTLS. Leave on — almost every provider wants it.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_user',
            field=models.CharField(blank=True, help_text='The account that sends the mail, e.g. you@gmail.com', max_length=200),
        ),
    ]
