# Generated by Django 6.1 on 2026-09-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_sitesettings_email_enabled_sitesettings_email_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('precision', 'Precision — cool slate and cyan'), ('warm', 'Warm — charcoal and amber')], default='precision', help_text="The app's look. Both dark; pick whichever suits the workshop.", max_length=10),
        ),
    ]
