# Generated by Django 6.1 on 2026-09-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_shoppinglistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_branding',
            field=models.BooleanField(default=True, help_text='Show the sethsparts brand ("Seth\'s Parts") above the shop name in the header. Untick to show only your own name.'),
        ),
    ]
