# Generated by Django 6.1 on 2026-09-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_sitesettings_show_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakenote',
            name='bin',
            field=models.ForeignKey(blank=True, help_text='The specific bin within a drawer, when known.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_notes', to='inventory.bin'),
        ),
        migrations.AddField(
            model_name='intakenote',
            name='drawer',
            field=models.ForeignKey(blank=True, help_text='The cabinet drawer this belongs in, when it has a permanent home.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_notes', to='inventory.drawer'),
        ),
        migrations.AlterField(
            model_name='intakenote',
            name='container',
            field=models.ForeignKey(blank=True, help_text='The box/tote this was captured against — the moving-day case.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_notes', to='inventory.container'),
        ),
    ]
