# Generated by Django 6.1 on 2026-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_intakenote_bin_intakenote_drawer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_onscreen_keyboard',
            field=models.BooleanField(default=True, help_text='Show the on-screen keyboard button on the Pi kiosk. Untick if the workshop has a physical keyboard.'),
        ),
    ]
