# Generated by Django 6.1 on 2026-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_sitesettings_show_onscreen_keyboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, help_text='DeepSeek API key for the enrichment suggestions.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tavily_api_key',
            field=models.CharField(blank=True, help_text='Tavily API key for the web-research step (product pages, datasheets, pricing).', max_length=200),
        ),
    ]
