# Generated by Django 6.1 on 2026-09-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_sitesettings_deepseek_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feedback_email',
            field=models.CharField(blank=True, help_text='Where in-app feedback (bug reports, feature requests) is sent. Blank means the feedback form offers copy-to-clipboard instead of sending.', max_length=200),
        ),
    ]
