# Generated by Django 6.1 on 2026-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_sitesettings_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.CharField(blank=True, help_text="Typical price as text, e.g. '£0.42' or '£3.50 / 100' — filled from web research when known.", max_length=80),
        ),
    ]
