# Generated by Django 6.1 on 2026-09-19 17:25

from django.db import migrations, models


def zero_bins_for_cabinet_four(apps, schema_editor):
    """Cabinet 4 (container #119) holds oversized items with no bin subdivisions. It has
    no Bin rows, so its drawers must default to bin_count=0 rather than 16."""
    Drawer = apps.get_model("inventory", "Drawer")
    Drawer.objects.filter(container__number=119).update(bin_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawer',
            name='bin_columns',
            field=models.PositiveSmallIntegerField(default=4, help_text='Columns in the printed grid, matching the physical layout'),
        ),
        migrations.AddField(
            model_name='drawer',
            name='bin_count',
            field=models.PositiveSmallIntegerField(default=16, help_text='Bin slots in this drawer (0 = no bins, up to 100)'),
        ),
        migrations.RunPython(zero_bins_for_cabinet_four, migrations.RunPython.noop),
    ]
