"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Overridden via the DJANGO_SECRET_KEY env var when this is deployed (Phase 6).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-cd7ren=%c#^o@2u$di-$(l-snw=s*_kv=euu@4$$li)s!03&aw",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h] or ["localhost", "127.0.0.1"]

# Traffic arrives via a Cloudflare Tunnel (cloudflared) which terminates TLS at
# Cloudflare's edge and forwards plain HTTP locally, setting X-Forwarded-Proto —
# without this Django would think every request is insecure.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS if h not in ("localhost", "127.0.0.1")]
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Renders every timestamp in the owner's configured timezone, and points a
    # browser at the setup wizard while setup is still outstanding. Both need to run
    # before anything renders, so they sit above the session/auth layers.
    'inventory.middleware.SiteTimezoneMiddleware',
    'inventory.middleware.SetupRedirectMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Site name and which optional hardware this install has, so
                # templates can hide what isn't configured instead of offering
                # buttons that fail.
                'inventory.context_processors.site_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get("DJANGO_DB_PATH", BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Hashed static filenames so a deploy's new CSS/JS is never served stale from a
# browser or CDN cache: the filename changes, so every caching layer misses and
# re-fetches. (Django 6.x configures storage via STORAGES, not STATICFILES_STORAGE.)
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "config.storage.LooseManifestStaticFilesStorage"},
}

# Part/reference-doc attachments (datasheets, pinouts, images).
MEDIA_URL = 'media/'
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT", BASE_DIR / 'media')

# Django's 2.5MB default is too small for phone camera photos.
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# The app's own login page, not the admin's. `@login_required` sends people here, and
# so does anyone who types /login/ — which used to be a 404 while the root URL greeted
# a visitor with a page branded "Django administration". Neither is a good front door
# for a project other people are meant to clone and run. The admin keeps its own
# /admin/login/ for the admin itself; that is untouched and still works.
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Long-lived sessions -- the Pi kiosk display logs in once and should stay logged in
# indefinitely rather than getting kicked back to the login page after Django's
# 2-week default. Doesn't weaken anything meaningfully since this is a single-operator
# site behind its own login already.
SESSION_COOKIE_AGE = int(os.environ.get("SESSION_COOKIE_AGE", 60 * 60 * 24 * 365))
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Shared secret for the machine-to-machine voice-search API (Home Assistant Assist calls
# it directly, so it can't use session login). Empty means the endpoint always rejects.
VOICE_SEARCH_API_KEY = os.environ.get("VOICE_SEARCH_API_KEY", "")

# LLM-assisted enrichment (DeepSeek). Empty means the suggest button stays hidden
# until the owner supplies their own key — the same opt-in shape as SMTP/Gmail.
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEEPSEEK_MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-chat") or "deepseek-chat"

# LED "find the part" indicator controller (Phase 8 backlog item — the Pi host doesn't exist
# yet). Empty URL means the locate button just reports "not configured" instead of erroring.
LED_CONTROLLER_URL = os.environ.get("LED_CONTROLLER_URL", "")
LED_CONTROLLER_KEY = os.environ.get("LED_CONTROLLER_KEY", "")

# Zebra GK420T label printer, connected via USB to the same Pi as the LED controller — a
# thin print-bridge there relays raw ZPL bytes straight to the printer. Empty URL means the
# print button just reports "not configured" instead of erroring.
LABEL_PRINTER_URL = os.environ.get("LABEL_PRINTER_URL", "")
LABEL_PRINTER_KEY = os.environ.get("LABEL_PRINTER_KEY", "")

# Archiving external documents (see inventory/archiving.py). When an owner adds a link
# to a datasheet or a reference, the app fetches a local copy and serves that instead,
# because the originals rot. Set this false to keep links without ever fetching them —
# the right choice for anyone who does not want the app making outbound requests.
# The database value in SiteSettings takes precedence over these for the hardware
# addresses above; these are the fallback, and the only source for the archive knobs.
ARCHIVE_ON_SAVE = os.environ.get("ARCHIVE_ON_SAVE", "true").lower() == "true"
ARCHIVE_TIMEOUT = int(os.environ.get("ARCHIVE_TIMEOUT", "20"))

# Checking GitHub for a newer version. This is the app's only outbound call that isn't
# to hardware the owner configured or a link they added, so it is off-switchable and
# the settings page says plainly what it does. Set UPDATE_REPO when running a fork, so
# the check follows that repository instead.
UPDATE_CHECK_ENABLED = os.environ.get("UPDATE_CHECK_ENABLED", "true").lower() == "true"
UPDATE_REPO = os.environ.get("UPDATE_REPO", "sethmills/sethsparts")

# Lets the Pi kiosk's own launch script auto-establish a real, properly-issued session
# on every boot (device-pairing style) without ever storing or typing Seth's account
# password anywhere. Empty means the endpoint always rejects.
KIOSK_AUTOLOGIN_TOKEN = os.environ.get("KIOSK_AUTOLOGIN_TOKEN", "")
KIOSK_AUTOLOGIN_USERNAME = os.environ.get("KIOSK_AUTOLOGIN_USERNAME", "")


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
