"""Incoming package for the inventory views, split out of the single 1465-line
views.py that used to live here.

Every name is re-exported here, so both of the existing call patterns keep
working unchanged:

  * `from . import views` + `views.browse`   (inventory/urls.py)
  * `from inventory.views import _locate_drawer`   (the test suite)

This file exists ONLY to keep those import paths stable. Add new views to the
topic module they belong to, not here.
"""
from ._shared import (
    _current_stock,
    _reorder_link,
    _consume_stock,
    _slugify_drawer_code,
    _location_choices,
    _drawer_number,
)
from .auth import (
    AppLoginView,
    AppLogoutView,
    kiosk_autologin,
)
from .browse import (
    browse,
    scan,
    go,
    jump_to_container,
    container_detail,
    delete_container,
    drawer_detail,
    register_container_barcode,
    register_drawer_barcode,
)
from .parts import (
    part_intake,
    part_detail,
    part_edit,
    add_part_photo,
    update_stock_quantity,
    update_stock_bin,
    delete_stock_item,
    add_stock_item,
)
from .audit_log import audit_log
from .searching import (
    parts_search,
    api_locate_part,
    api_add_intake_note,
)
from .tagging import (
    tagging_list,
    tagging_update,
    _tagging_location_choices,
)
from .bins import (
    BINS_PER_DRAWER,
    MAX_BINS,
    _bin_eligible_drawers,
    _ensure_bins_seeded,
    _ensure_bins_for_drawer,
    bin_setup,
    bin_scan,
    api_scan_bin,
    bin_detail,
    register_bin_barcode,
    add_sub_bin,
    register_sub_bin_barcode,
    delete_sub_bin,
    print_bin_grid,
    update_drawer_bins,
)
from .labels import (
    labels,
    generate_and_print_labels,
    print_labels,
    barcode_svg,
    custom_label,
)
from .intake import (
    quick_add_container,
    add_container_photo,
    add_intake_note,
    bulk_intake,
    add_intake_location,
    intake_queue,
    assign_intake_note_container,
    mark_intake_note_reviewed,
)
from .projects import (
    project_list,
    create_project,
    project_detail,
    build_project,
    reorder,
)
from .pick import pick
from .enrichment import (
    enrichment_queue,
    run_enrichment_classification,
    flag_part_for_enrichment,
    bulk_classify,
    enrich_pending_with_ai,
    ai_scan_candidates,
    export_inventory,
    resistor_calculator,
)
from .import_export import (
    export_csv,
    import_csv,
)
from .shopping import (
    shopping_list,
    shopping_list_add,
    shopping_list_clear,
    shopping_list_export,
    shopping_list_toggle,
)
from .community import (
    api_community_claim,
    api_community_messages,
    api_community_peer_search,
    api_community_pins,
    community_block,
    community_connections,
    community_forget,
    community_issue_code,
    community_join,
    community_map,
    community_message_inbox,
    community_message_thread,
    community_network_search,
    community_retry_message,
    community_revoke,
    community_send_message,
    community_sync_pins,
    community_unblock,
    community_update_peer,
)
from .help import (
    help_index,
    help_topic,
    feedback,
    api_feedback,
)
from .setup import (
    setup_hub,
    setup_account,
    setup_site,
    setup_lights,
    setup_flash,
    setup_printer,
    setup_reference,
    setup_community,
    setup_access,
    setup_email,
    setup_ai,
    setup_finish,
)
from .reference import (
    reference_list,
    reference_manage,
    reference_add,
    reference_edit,
    reference_delete,
    reference_move,
    reference_archive,
    reference_category_add,
    reference_category_edit,
    reference_category_delete,
)
from .lights import (
    _led_post,
    _locate_drawer,
    locate_drawer_led,
    locate_stock_item,
    locate_bin,
    light_controls,
    led_set_defaults,
    led_room_light,
    led_demo,
)

__all__ = [
    "_current_stock",
    "_reorder_link",
    "_consume_stock",
    "_slugify_drawer_code",
    "_location_choices",
    "_drawer_number",
    "AppLoginView",
    "AppLogoutView",
    "kiosk_autologin",
    "browse",
    "scan",
    "go",
    "jump_to_container",
    "container_detail",
    "delete_container",
    "drawer_detail",
    "register_container_barcode",
    "register_drawer_barcode",
    "part_intake",
    "part_detail",
    "part_edit",
    "add_part_photo",
    "update_stock_quantity",
    "update_stock_bin",
    "delete_stock_item",
    "add_stock_item",
    "audit_log",
    "parts_search",
    "api_locate_part",
    "api_add_intake_note",
    "tagging_list",
    "tagging_update",
    "_tagging_location_choices",
    "BINS_PER_DRAWER",
    "MAX_BINS",
    "_bin_eligible_drawers",
    "_ensure_bins_seeded",
    "_ensure_bins_for_drawer",
    "bin_setup",
    "bin_scan",
    "api_scan_bin",
    "bin_detail",
    "register_bin_barcode",
    "add_sub_bin",
    "register_sub_bin_barcode",
    "delete_sub_bin",
    "print_bin_grid",
    "update_drawer_bins",
    "labels",
    "generate_and_print_labels",
    "print_labels",
    "barcode_svg",
    "custom_label",
    "quick_add_container",
    "add_container_photo",
    "add_intake_note",
    "bulk_intake",
    "add_intake_location",
    "intake_queue",
    "assign_intake_note_container",
    "mark_intake_note_reviewed",
    "project_list",
    "create_project",
    "project_detail",
    "build_project",
    "pick",
    "reorder",
    "enrichment_queue",
    "run_enrichment_classification",
    "flag_part_for_enrichment",
    "bulk_classify",
    "enrich_pending_with_ai",
    "ai_scan_candidates",
    "export_inventory",
    "export_csv",
    "import_csv",
    "shopping_list",
    "shopping_list_add",
    "shopping_list_toggle",
    "shopping_list_clear",
    "shopping_list_export",
    "setup_hub",
    "setup_account",
    "setup_site",
    "setup_lights",
    "setup_flash",
    "setup_printer",
    "setup_reference",
    "setup_community",
    "setup_access",
    "setup_email",
    "setup_ai",
    "setup_finish",
    "community_connections",
    "community_map",
    "community_network_search",
    "community_sync_pins",
    "community_join",
    "community_issue_code",
    "community_update_peer",
    "community_revoke",
    "community_forget",
    "community_message_inbox",
    "community_message_thread",
    "community_send_message",
    "community_retry_message",
    "community_block",
    "community_unblock",
    "api_community_claim",
    "api_community_peer_search",
    "api_community_pins",
    "api_community_messages",
    "help_index",
    "help_topic",
    "feedback",
    "api_feedback",
    "reference_list",
    "reference_manage",
    "reference_add",
    "reference_edit",
    "reference_delete",
    "reference_move",
    "reference_archive",
    "reference_category_add",
    "reference_category_edit",
    "reference_category_delete",
    "resistor_calculator",
    "_led_post",
    "_locate_drawer",
    "locate_drawer_led",
    "locate_stock_item",
    "locate_bin",
    "light_controls",
    "led_set_defaults",
    "led_room_light",
    "led_demo",
]
